-- Mapeamento de macro_category/category para serviços nativos existentes
UPDATE public.services SET
  macro_category = m.macro,
  category = m.cat
FROM (VALUES
  ('1ª Consulta','Consulta','1ª Consulta'),
  ('1ª Consulta Online','Consulta','1ª Consulta (Online)'),
  ('Avaliação Pré-Consulta','Consulta','1ª Consulta'),
  ('Consulta de Retorno','Consulta','Consulta Seguimento'),
  ('Consulta de Retorno Online','Consulta','Consulta Seguimento (Online)'),
  ('Consulta de Seguimento','Consulta','Consulta Seguimento'),
  ('Consulta de Seguimento Online','Consulta','Consulta Seguimento (Online)'),
  ('Consulta cardiológica','Consulta','Consulta Seguimento'),
  ('Consulta cirúrgica','Consulta','Consulta Seguimento'),
  ('Consulta clínica','Consulta','Consulta Seguimento'),
  ('Consulta dermatológica','Consulta','Consulta Seguimento'),
  ('Consulta endócrino','Consulta','Consulta Seguimento'),
  ('Consulta gastro','Consulta','Consulta Seguimento'),
  ('Consulta ginecológica','Consulta','Consulta Seguimento'),
  ('Consulta neurológica','Consulta','Consulta Seguimento'),
  ('Consulta Nutricionista','Consulta','Consulta Parceiros'),
  ('Consulta nutrológica','Consulta','Consulta Seguimento'),
  ('Consulta oftalmológica','Consulta','Consulta Seguimento'),
  ('Consulta ortopédica','Consulta','Consulta Seguimento'),
  ('Consulta otorrino','Consulta','Consulta Seguimento'),
  ('Consulta pediátrica','Consulta','Consulta Seguimento'),
  ('Consulta pneumológica','Consulta','Consulta Seguimento'),
  ('Consulta Psicólogo(a)','Consulta','Consulta Parceiros'),
  ('Consulta psiquiátrica','Consulta','Consulta Seguimento'),
  ('Consulta reumatológica','Consulta','Consulta Seguimento'),
  ('Consulta urológica','Consulta','Consulta Seguimento'),
  ('Pré-natal','Consulta','Consulta Seguimento'),
  ('Puericultura','Consulta','Consulta Seguimento'),
  ('Botox','Estética','Toxina Botulínica'),
  ('Botox - Axilas','Estética','Toxina Botulínica'),
  ('Botox - Rosto','Estética','Toxina Botulínica'),
  ('Botox - Rosto e Pescoço','Estética','Toxina Botulínica'),
  ('Preenchimento','Estética','Preenchedores'),
  ('Profhilo','Estética','Preenchedores'),
  ('Radiesse (2 seringas)','Estética','Bioestimuladores'),
  ('Radiesse (4 seringas)','Estética','Bioestimuladores'),
  ('Sculptra','Estética','Bioestimuladores'),
  ('Bioestimulador injetável','Estética','Bioestimuladores'),
  ('Liftera','Estética','Tecnologias Estética'),
  ('Liftera flacidez','Estética','Tecnologias Estética'),
  ('Liftera olheiras','Estética','Tecnologias Estética'),
  ('Liftera papada','Estética','Tecnologias Estética'),
  ('Liftera Pescoço','Estética','Tecnologias Estética'),
  ('Liftera rejuvenescimento','Estética','Tecnologias Estética'),
  ('Laser ablativo - dual mode','Estética','Tecnologias Estética'),
  ('Laser dermatológico','Estética','Tecnologias Estética'),
  ('Laser vaginal','Estética','Tecnologias Estética'),
  ('Luz pulsada acne','Estética','Tecnologias Estética'),
  ('Luz pulsada mãos','Estética','Tecnologias Estética'),
  ('Lumina eye peel','Estética','Tecnologias Estética'),
  ('Radiofrequência','Estética','Tecnologias Estética'),
  ('Dual mode corporal','Estética','Tecnologias Estética'),
  ('Dual mode olheiras','Estética','Tecnologias Estética'),
  ('Eletroporação','Estética','Tecnologias Estética'),
  ('Acroma','Estética','Tratamentos rosto'),
  ('Acroma Melasma','Estética','Tratamentos rosto'),
  ('Acroma Olheiras','Estética','Tratamentos rosto'),
  ('Lha la peel','Estética','Tratamentos rosto'),
  ('Limpeza de Pele','Estética','Tratamentos rosto'),
  ('Peeling','Estética','Tratamentos rosto'),
  ('Peeling 4D','Estética','Tratamentos rosto'),
  ('Tratamento de acne','Estética','Tratamentos rosto'),
  ('Intradermo','Estética','Tratamentos rosto'),
  ('Drenagem','Estética','Tratamentos corporais'),
  ('Clareamento íntimo','Estética','Tratamentos corporais'),
  ('Emagrecimento','Estética','Tratamentos corporais'),
  ('MMP Capilar','Estética','Capilares'),
  ('Microagulhamento','Estética','Microagulhamento'),
  ('Soro - AlfaLipoico','Endovenoso','Antiinflamatórios'),
  ('Soro - Antioxidante','Endovenoso','Antiinflamatórios'),
  ('Soro - Azul de Metileno','Endovenoso','Protocolos complexos'),
  ('Soro - Ferro','Endovenoso','Reposição de ferro'),
  ('Soro - Hidrocortisona','Endovenoso','Antiinflamatórios'),
  ('Soro - Mitocondrial','Endovenoso','Protocolos complexos'),
  ('Soro - Outros','Endovenoso','Protocolos complexos'),
  ('Soro - Performance','Endovenoso','Aceleradores Metabólicos'),
  ('Soro - Pele, cabelo e unha','Endovenoso','Vitaminas e Minerais'),
  ('Soro - Queima de gordura','Endovenoso','Aceleradores Metabólicos'),
  ('Soro - Vitamina B12','Endovenoso','Vitaminas e Minerais'),
  ('Soro - Vitamina C','Endovenoso','Vitaminas e Minerais'),
  ('Noripurum','Endovenoso','Reposição de ferro'),
  ('L-Carnitina + cafeína','Endovenoso','Aceleradores Metabólicos'),
  ('Curcumina','Endovenoso','Antiinflamatórios'),
  ('Infusão de Cetamina','Endovenoso','Protocolos complexos'),
  ('Cetamina Assistida','Endovenoso','Protocolos complexos'),
  ('Sangria Terapêutica','Endovenoso','Protocolos complexos'),
  ('Cipionato de Testosterona','Intramuscular','Aplicação de hormônios (IM)'),
  ('Enantato de Testosterona','Intramuscular','Aplicação de hormônios (IM)'),
  ('Deposteron','Intramuscular','Aplicação de hormônios (IM)'),
  ('Nandrolona','Intramuscular','Aplicação de hormônios (IM)'),
  ('GH','Intramuscular','Aplicação de hormônios (IM)'),
  ('HCG','Intramuscular','Aplicação de hormônios (IM)'),
  ('Cortisol','Intramuscular','Antiinflamatórios (IM)'),
  ('Triancinolona','Intramuscular','Antiinflamatórios (IM)'),
  ('Vitamina D3 - 600.000ui','Intramuscular','Vitaminas e Minerais (IM)'),
  ('Terapia hormonal masculina','Intramuscular','Aplicação de hormônios (IM)'),
  ('Terapias injetáveis','Intramuscular','Protocolos complexos (IM)'),
  ('Mounjaro/Tirzepatida - 2,5mg','Subcutâneo','Emagrecedores'),
  ('Mounjaro/Tirzepatida - 5mg','Subcutâneo','Emagrecedores'),
  ('Mounjaro/Tirzepatida - 7,5mg','Subcutâneo','Emagrecedores'),
  ('Mounjaro/Tirzepatida - 10mg','Subcutâneo','Emagrecedores'),
  ('Mounjaro/Tirzepatida - 12,5mg','Subcutâneo','Emagrecedores'),
  ('Mounjaro/Tirzepatida - frasco 60mg','Subcutâneo','Emagrecedores'),
  ('Mounjaro/Tirzepatida - frasco 90mg','Subcutâneo','Emagrecedores'),
  ('Implante - Base','Implante','Implante Hormonal - Pellet'),
  ('Implante - Adicional','Implante','Implante Hormonal - Pellet'),
  ('Audiometria','Exames','Avaliação Clínica'),
  ('Bioimpedância','Exames','Bioimpedância'),
  ('Calorimetria','Exames','Calorimetria'),
  ('Check-up cardíaco','Exames','Check-up'),
  ('Check-up geral','Exames','Check-up'),
  ('Eletrocardiograma','Exames','Avaliação Clínica'),
  ('Eletroencefalograma','Exames','Avaliação Clínica'),
  ('Espirometria','Exames','Avaliação Clínica'),
  ('Exame de próstata','Exames','Avaliação Clínica'),
  ('Exame de vista','Exames','Exame de vista'),
  ('Mapeamento de retina','Exames','Exame de vista'),
  ('Teste ergométrico','Exames','Avaliação Clínica'),
  ('Avaliação de desenvolvimento','Exames','Avaliação Clínica'),
  ('Avaliação de lesão','Exames','Avaliação Clínica'),
  ('Avaliação diagnóstica','Exames','Avaliação Clínica'),
  ('Avaliação metabólica','Exames','Avaliação Clínica'),
  ('Avaliação neurológica','Exames','Avaliação Clínica'),
  ('Avaliação pré-operatória','Exames','Avaliação Clínica'),
  ('Coleta de Sangue','Exames Laboratoriais','Coleta de Sangue'),
  ('Preventivo (Papanicolau)','Exames Laboratoriais','Coleta de Preventivo'),
  ('Colposcopia','Exames Laboratoriais','Coleta de Preventivo'),
  ('Biópsia','Exames Laboratoriais','Coleta de Sangue'),
  ('Ultrassom','Exames de Imagem','Ultrassom'),
  ('Ultrassonografia obstétrica','Exames de Imagem','Ultrassom'),
  ('Colonoscopia','Procedimentos','Procedimento minimamente invasivo'),
  ('CPRE','Procedimentos','Procedimento minimamente invasivo'),
  ('Dilatação Endoscópica','Procedimentos','Procedimento minimamente invasivo'),
  ('Dilatação Segmentar','Procedimentos','Procedimento minimamente invasivo'),
  ('ECT','Procedimentos','Procedimento minimamente invasivo'),
  ('Endoscopia','Procedimentos','Procedimento minimamente invasivo'),
  ('Endoscopia nasal','Procedimentos','Procedimento minimamente invasivo'),
  ('EMT','Procedimentos','Procedimento minimamente invasivo'),
  ('Gastroplastia Endoscópica (sutura)','Procedimentos','Procedimento minimamente invasivo'),
  ('Gastrostomia Endoscópica','Procedimentos','Procedimento minimamente invasivo'),
  ('Hemostasia Mecânica','Procedimentos','Procedimento minimamente invasivo'),
  ('Hemostasia Térmica','Procedimentos','Procedimento minimamente invasivo'),
  ('Histeroscopia','Procedimentos','Procedimento minimamente invasivo'),
  ('Mucosectomia em Colonoscopia','Procedimentos','Procedimento minimamente invasivo'),
  ('Mucosectomia em Endoscopia','Procedimentos','Procedimento minimamente invasivo'),
  ('Passagem de sonda por Endoscopia','Procedimentos','Procedimento minimamente invasivo'),
  ('Plasma de argônio','Procedimentos','Procedimento minimamente invasivo'),
  ('Polipectomia em Colonoscopia','Procedimentos','Procedimento minimamente invasivo'),
  ('Polipectomia em Endoscopia','Procedimentos','Procedimento minimamente invasivo'),
  ('Inserção de DIU','Procedimentos','Procedimento minimamente invasivo'),
  ('Infiltração','Procedimentos','Procedimento minimamente invasivo'),
  ('Infiltração articular','Procedimentos','Procedimento minimamente invasivo'),
  ('Imobilização','Procedimentos','Procedimento minimamente invasivo'),
  ('Exerese','Procedimentos','Procedimento minimamente invasivo'),
  ('Pequenas cirurgias','Procedimentos','Procedimento minimamente invasivo'),
  ('Procedimentos de ouvido/nariz','Procedimentos','Procedimento minimamente invasivo'),
  ('Retirada de corpo estranho','Procedimentos','Procedimento minimamente invasivo'),
  ('Colocação de Balão Intragástrico (1 ano)','Procedimentos','Procedimento minimamente invasivo'),
  ('Colocação de Balão Intragástrico (6 meses)','Procedimentos','Procedimento minimamente invasivo'),
  ('Cirurgia refrativa','Procedimentos','Cirurgia em centro cirúrgico'),
  ('Vasectomia','Procedimentos','Cirurgia em centro cirúrgico'),
  ('Plano de Acompanhamento','Plano de Acompanhamento','Plano de Acompanhamento'),
  ('Plano de Acompanhamento - 2 meses','Plano de Acompanhamento','Plano de Acompanhamento'),
  ('Plano de Acompanhamento - 3 meses','Plano de Acompanhamento','Plano de Acompanhamento'),
  ('Plano de Acompanhamento - 6 meses','Plano de Acompanhamento','Plano de Acompanhamento'),
  ('Plano de Acompanhamento - 12 meses','Plano de Acompanhamento','Plano de Acompanhamento'),
  ('Sublocação','Sublocação','Sublocação de espaço fixo'),
  ('Repasse parceiros','Sublocação','Sublocação de espaço variável'),
  ('Acompanhamento medicamentoso','Outros','Outros'),
  ('Gestão de doenças crônicas','Outros','Outros'),
  ('Medicação - Venvanse','Outros','Outros'),
  ('Outras medicações','Outros','Outros'),
  ('Suplementação','Outros','Outros'),
  ('Tratamento de dor crônica','Outros','Outros'),
  ('Tratamento digestivo','Outros','Outros'),
  ('Tratamento hormonal','Outros','Outros'),
  ('Tratamento respiratório','Outros','Outros')
) AS m(name, macro, cat)
WHERE public.services.name = m.name
  AND (public.services.macro_category IS NULL OR public.services.macro_category = '');

-- Atualiza seed_native_services para gravar macro/category em novas clínicas
CREATE OR REPLACE FUNCTION public.seed_native_services(p_clinic_id uuid)
 RETURNS void
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
BEGIN
  INSERT INTO services (clinic_id, name, macro_category, category, active) VALUES
    (p_clinic_id, '1ª Consulta', 'Consulta', '1ª Consulta', false),
    (p_clinic_id, '1ª Consulta Online', 'Consulta', '1ª Consulta (Online)', false),
    (p_clinic_id, 'Avaliação Pré-Consulta', 'Consulta', '1ª Consulta', false),
    (p_clinic_id, 'Consulta de Retorno', 'Consulta', 'Consulta Seguimento', false),
    (p_clinic_id, 'Consulta de Retorno Online', 'Consulta', 'Consulta Seguimento (Online)', false),
    (p_clinic_id, 'Consulta de Seguimento', 'Consulta', 'Consulta Seguimento', false),
    (p_clinic_id, 'Consulta de Seguimento Online', 'Consulta', 'Consulta Seguimento (Online)', false),
    (p_clinic_id, 'Acompanhamento medicamentoso', 'Outros', 'Outros', false),
    (p_clinic_id, 'Acroma', 'Estética', 'Tratamentos rosto', false),
    (p_clinic_id, 'Acroma Melasma', 'Estética', 'Tratamentos rosto', false),
    (p_clinic_id, 'Acroma Olheiras', 'Estética', 'Tratamentos rosto', false),
    (p_clinic_id, 'Audiometria', 'Exames', 'Avaliação Clínica', false),
    (p_clinic_id, 'Avaliação de desenvolvimento', 'Exames', 'Avaliação Clínica', false),
    (p_clinic_id, 'Avaliação de lesão', 'Exames', 'Avaliação Clínica', false),
    (p_clinic_id, 'Avaliação diagnóstica', 'Exames', 'Avaliação Clínica', false),
    (p_clinic_id, 'Avaliação metabólica', 'Exames', 'Avaliação Clínica', false),
    (p_clinic_id, 'Avaliação neurológica', 'Exames', 'Avaliação Clínica', false),
    (p_clinic_id, 'Avaliação pré-operatória', 'Exames', 'Avaliação Clínica', false),
    (p_clinic_id, 'Bioestimulador injetável', 'Estética', 'Bioestimuladores', false),
    (p_clinic_id, 'Bioimpedância', 'Exames', 'Bioimpedância', false),
    (p_clinic_id, 'Biópsia', 'Exames Laboratoriais', 'Coleta de Sangue', false),
    (p_clinic_id, 'Botox', 'Estética', 'Toxina Botulínica', false),
    (p_clinic_id, 'Botox - Axilas', 'Estética', 'Toxina Botulínica', false),
    (p_clinic_id, 'Botox - Rosto', 'Estética', 'Toxina Botulínica', false),
    (p_clinic_id, 'Botox - Rosto e Pescoço', 'Estética', 'Toxina Botulínica', false),
    (p_clinic_id, 'Calorimetria', 'Exames', 'Calorimetria', false),
    (p_clinic_id, 'Cetamina Assistida', 'Endovenoso', 'Protocolos complexos', false),
    (p_clinic_id, 'Check-up cardíaco', 'Exames', 'Check-up', false),
    (p_clinic_id, 'Check-up geral', 'Exames', 'Check-up', false),
    (p_clinic_id, 'Cipionato de Testosterona', 'Intramuscular', 'Aplicação de hormônios (IM)', false),
    (p_clinic_id, 'Cirurgia refrativa', 'Procedimentos', 'Cirurgia em centro cirúrgico', false),
    (p_clinic_id, 'Clareamento íntimo', 'Estética', 'Tratamentos corporais', false),
    (p_clinic_id, 'Coleta de Sangue', 'Exames Laboratoriais', 'Coleta de Sangue', false),
    (p_clinic_id, 'Colocação de Balão Intragástrico (1 ano)', 'Procedimentos', 'Procedimento minimamente invasivo', false),
    (p_clinic_id, 'Colocação de Balão Intragástrico (6 meses)', 'Procedimentos', 'Procedimento minimamente invasivo', false),
    (p_clinic_id, 'Colonoscopia', 'Procedimentos', 'Procedimento minimamente invasivo', false),
    (p_clinic_id, 'Colposcopia', 'Exames Laboratoriais', 'Coleta de Preventivo', false),
    (p_clinic_id, 'Consulta cardiológica', 'Consulta', 'Consulta Seguimento', false),
    (p_clinic_id, 'Consulta cirúrgica', 'Consulta', 'Consulta Seguimento', false),
    (p_clinic_id, 'Consulta clínica', 'Consulta', 'Consulta Seguimento', false),
    (p_clinic_id, 'Consulta dermatológica', 'Consulta', 'Consulta Seguimento', false),
    (p_clinic_id, 'Consulta endócrino', 'Consulta', 'Consulta Seguimento', false),
    (p_clinic_id, 'Consulta gastro', 'Consulta', 'Consulta Seguimento', false),
    (p_clinic_id, 'Consulta ginecológica', 'Consulta', 'Consulta Seguimento', false),
    (p_clinic_id, 'Consulta neurológica', 'Consulta', 'Consulta Seguimento', false),
    (p_clinic_id, 'Consulta Nutricionista', 'Consulta', 'Consulta Parceiros', false),
    (p_clinic_id, 'Consulta nutrológica', 'Consulta', 'Consulta Seguimento', false),
    (p_clinic_id, 'Consulta oftalmológica', 'Consulta', 'Consulta Seguimento', false),
    (p_clinic_id, 'Consulta ortopédica', 'Consulta', 'Consulta Seguimento', false),
    (p_clinic_id, 'Consulta otorrino', 'Consulta', 'Consulta Seguimento', false),
    (p_clinic_id, 'Consulta pediátrica', 'Consulta', 'Consulta Seguimento', false),
    (p_clinic_id, 'Consulta pneumológica', 'Consulta', 'Consulta Seguimento', false),
    (p_clinic_id, 'Consulta Psicólogo(a)', 'Consulta', 'Consulta Parceiros', false),
    (p_clinic_id, 'Consulta psiquiátrica', 'Consulta', 'Consulta Seguimento', false),
    (p_clinic_id, 'Consulta reumatológica', 'Consulta', 'Consulta Seguimento', false),
    (p_clinic_id, 'Consulta urológica', 'Consulta', 'Consulta Seguimento', false),
    (p_clinic_id, 'Cortisol', 'Intramuscular', 'Antiinflamatórios (IM)', false),
    (p_clinic_id, 'CPRE', 'Procedimentos', 'Procedimento minimamente invasivo', false),
    (p_clinic_id, 'Curcumina', 'Endovenoso', 'Antiinflamatórios', false),
    (p_clinic_id, 'Deposteron', 'Intramuscular', 'Aplicação de hormônios (IM)', false),
    (p_clinic_id, 'Dilatação Endoscópica', 'Procedimentos', 'Procedimento minimamente invasivo', false),
    (p_clinic_id, 'Dilatação Segmentar', 'Procedimentos', 'Procedimento minimamente invasivo', false),
    (p_clinic_id, 'Drenagem', 'Estética', 'Tratamentos corporais', false),
    (p_clinic_id, 'Dual mode corporal', 'Estética', 'Tecnologias Estética', false),
    (p_clinic_id, 'Dual mode olheiras', 'Estética', 'Tecnologias Estética', false),
    (p_clinic_id, 'ECT', 'Procedimentos', 'Procedimento minimamente invasivo', false),
    (p_clinic_id, 'Eletrocardiograma', 'Exames', 'Avaliação Clínica', false),
    (p_clinic_id, 'Eletroencefalograma', 'Exames', 'Avaliação Clínica', false),
    (p_clinic_id, 'Eletroporação', 'Estética', 'Tecnologias Estética', false),
    (p_clinic_id, 'Emagrecimento', 'Estética', 'Tratamentos corporais', false),
    (p_clinic_id, 'EMT', 'Procedimentos', 'Procedimento minimamente invasivo', false),
    (p_clinic_id, 'Enantato de Testosterona', 'Intramuscular', 'Aplicação de hormônios (IM)', false),
    (p_clinic_id, 'Endoscopia', 'Procedimentos', 'Procedimento minimamente invasivo', false),
    (p_clinic_id, 'Endoscopia nasal', 'Procedimentos', 'Procedimento minimamente invasivo', false),
    (p_clinic_id, 'Espirometria', 'Exames', 'Avaliação Clínica', false),
    (p_clinic_id, 'Exame de próstata', 'Exames', 'Avaliação Clínica', false),
    (p_clinic_id, 'Exame de vista', 'Exames', 'Exame de vista', false),
    (p_clinic_id, 'Exerese', 'Procedimentos', 'Procedimento minimamente invasivo', false),
    (p_clinic_id, 'Gastroplastia Endoscópica (sutura)', 'Procedimentos', 'Procedimento minimamente invasivo', false),
    (p_clinic_id, 'Gastrostomia Endoscópica', 'Procedimentos', 'Procedimento minimamente invasivo', false),
    (p_clinic_id, 'Gestão de doenças crônicas', 'Outros', 'Outros', false),
    (p_clinic_id, 'GH', 'Intramuscular', 'Aplicação de hormônios (IM)', false),
    (p_clinic_id, 'HCG', 'Intramuscular', 'Aplicação de hormônios (IM)', false),
    (p_clinic_id, 'Hemostasia Mecânica', 'Procedimentos', 'Procedimento minimamente invasivo', false),
    (p_clinic_id, 'Hemostasia Térmica', 'Procedimentos', 'Procedimento minimamente invasivo', false),
    (p_clinic_id, 'Histeroscopia', 'Procedimentos', 'Procedimento minimamente invasivo', false),
    (p_clinic_id, 'Imobilização', 'Procedimentos', 'Procedimento minimamente invasivo', false),
    (p_clinic_id, 'Implante - Adicional', 'Implante', 'Implante Hormonal - Pellet', false),
    (p_clinic_id, 'Implante - Base', 'Implante', 'Implante Hormonal - Pellet', false),
    (p_clinic_id, 'Infiltração', 'Procedimentos', 'Procedimento minimamente invasivo', false),
    (p_clinic_id, 'Infiltração articular', 'Procedimentos', 'Procedimento minimamente invasivo', false),
    (p_clinic_id, 'Infusão de Cetamina', 'Endovenoso', 'Protocolos complexos', false),
    (p_clinic_id, 'Inserção de DIU', 'Procedimentos', 'Procedimento minimamente invasivo', false),
    (p_clinic_id, 'Intradermo', 'Estética', 'Tratamentos rosto', false),
    (p_clinic_id, 'Laser ablativo - dual mode', 'Estética', 'Tecnologias Estética', false),
    (p_clinic_id, 'Laser dermatológico', 'Estética', 'Tecnologias Estética', false),
    (p_clinic_id, 'Laser vaginal', 'Estética', 'Tecnologias Estética', false),
    (p_clinic_id, 'L-Carnitina + cafeína', 'Endovenoso', 'Aceleradores Metabólicos', false),
    (p_clinic_id, 'Lha la peel', 'Estética', 'Tratamentos rosto', false),
    (p_clinic_id, 'Liftera', 'Estética', 'Tecnologias Estética', false),
    (p_clinic_id, 'Liftera flacidez', 'Estética', 'Tecnologias Estética', false),
    (p_clinic_id, 'Liftera olheiras', 'Estética', 'Tecnologias Estética', false),
    (p_clinic_id, 'Liftera papada', 'Estética', 'Tecnologias Estética', false),
    (p_clinic_id, 'Liftera Pescoço', 'Estética', 'Tecnologias Estética', false),
    (p_clinic_id, 'Liftera rejuvenescimento', 'Estética', 'Tecnologias Estética', false),
    (p_clinic_id, 'Limpeza de Pele', 'Estética', 'Tratamentos rosto', false),
    (p_clinic_id, 'Luz pulsada acne', 'Estética', 'Tecnologias Estética', false),
    (p_clinic_id, 'Lumina eye peel', 'Estética', 'Tecnologias Estética', false),
    (p_clinic_id, 'Luz pulsada mãos', 'Estética', 'Tecnologias Estética', false),
    (p_clinic_id, 'Mapeamento de retina', 'Exames', 'Exame de vista', false),
    (p_clinic_id, 'Medicação - Venvanse', 'Outros', 'Outros', false),
    (p_clinic_id, 'Microagulhamento', 'Estética', 'Microagulhamento', false),
    (p_clinic_id, 'MMP Capilar', 'Estética', 'Capilares', false),
    (p_clinic_id, 'Mounjaro/Tirzepatida - 2,5mg', 'Subcutâneo', 'Emagrecedores', false),
    (p_clinic_id, 'Mounjaro/Tirzepatida - 5mg', 'Subcutâneo', 'Emagrecedores', false),
    (p_clinic_id, 'Mounjaro/Tirzepatida - 7,5mg', 'Subcutâneo', 'Emagrecedores', false),
    (p_clinic_id, 'Mounjaro/Tirzepatida - 10mg', 'Subcutâneo', 'Emagrecedores', false),
    (p_clinic_id, 'Mounjaro/Tirzepatida - 12,5mg', 'Subcutâneo', 'Emagrecedores', false),
    (p_clinic_id, 'Mounjaro/Tirzepatida - frasco 60mg', 'Subcutâneo', 'Emagrecedores', false),
    (p_clinic_id, 'Mounjaro/Tirzepatida - frasco 90mg', 'Subcutâneo', 'Emagrecedores', false),
    (p_clinic_id, 'Mucosectomia em Colonoscopia', 'Procedimentos', 'Procedimento minimamente invasivo', false),
    (p_clinic_id, 'Mucosectomia em Endoscopia', 'Procedimentos', 'Procedimento minimamente invasivo', false),
    (p_clinic_id, 'Nandrolona', 'Intramuscular', 'Aplicação de hormônios (IM)', false),
    (p_clinic_id, 'Noripurum', 'Endovenoso', 'Reposição de ferro', false),
    (p_clinic_id, 'Outras medicações', 'Outros', 'Outros', false),
    (p_clinic_id, 'Passagem de sonda por Endoscopia', 'Procedimentos', 'Procedimento minimamente invasivo', false),
    (p_clinic_id, 'Peeling', 'Estética', 'Tratamentos rosto', false),
    (p_clinic_id, 'Peeling 4D', 'Estética', 'Tratamentos rosto', false),
    (p_clinic_id, 'Pequenas cirurgias', 'Procedimentos', 'Procedimento minimamente invasivo', false),
    (p_clinic_id, 'Plano de Acompanhamento', 'Plano de Acompanhamento', 'Plano de Acompanhamento', false),
    (p_clinic_id, 'Plano de Acompanhamento - 2 meses', 'Plano de Acompanhamento', 'Plano de Acompanhamento', false),
    (p_clinic_id, 'Plano de Acompanhamento - 3 meses', 'Plano de Acompanhamento', 'Plano de Acompanhamento', false),
    (p_clinic_id, 'Plano de Acompanhamento - 6 meses', 'Plano de Acompanhamento', 'Plano de Acompanhamento', false),
    (p_clinic_id, 'Plano de Acompanhamento - 12 meses', 'Plano de Acompanhamento', 'Plano de Acompanhamento', false),
    (p_clinic_id, 'Plasma de argônio', 'Procedimentos', 'Procedimento minimamente invasivo', false),
    (p_clinic_id, 'Polipectomia em Colonoscopia', 'Procedimentos', 'Procedimento minimamente invasivo', false),
    (p_clinic_id, 'Polipectomia em Endoscopia', 'Procedimentos', 'Procedimento minimamente invasivo', false),
    (p_clinic_id, 'Preenchimento', 'Estética', 'Preenchedores', false),
    (p_clinic_id, 'Pré-natal', 'Consulta', 'Consulta Seguimento', false),
    (p_clinic_id, 'Preventivo (Papanicolau)', 'Exames Laboratoriais', 'Coleta de Preventivo', false),
    (p_clinic_id, 'Procedimentos de ouvido/nariz', 'Procedimentos', 'Procedimento minimamente invasivo', false),
    (p_clinic_id, 'Profhilo', 'Estética', 'Preenchedores', false),
    (p_clinic_id, 'Puericultura', 'Consulta', 'Consulta Seguimento', false),
    (p_clinic_id, 'Radiesse (2 seringas)', 'Estética', 'Bioestimuladores', false),
    (p_clinic_id, 'Radiesse (4 seringas)', 'Estética', 'Bioestimuladores', false),
    (p_clinic_id, 'Radiofrequência', 'Estética', 'Tecnologias Estética', false),
    (p_clinic_id, 'Repasse parceiros', 'Sublocação', 'Sublocação de espaço variável', false),
    (p_clinic_id, 'Retirada de corpo estranho', 'Procedimentos', 'Procedimento minimamente invasivo', false),
    (p_clinic_id, 'Sangria Terapêutica', 'Endovenoso', 'Protocolos complexos', false),
    (p_clinic_id, 'Sculptra', 'Estética', 'Bioestimuladores', false),
    (p_clinic_id, 'Soro - AlfaLipoico', 'Endovenoso', 'Antiinflamatórios', false),
    (p_clinic_id, 'Soro - Antioxidante', 'Endovenoso', 'Antiinflamatórios', false),
    (p_clinic_id, 'Soro - Azul de Metileno', 'Endovenoso', 'Protocolos complexos', false),
    (p_clinic_id, 'Soro - Ferro', 'Endovenoso', 'Reposição de ferro', false),
    (p_clinic_id, 'Soro - Hidrocortisona', 'Endovenoso', 'Antiinflamatórios', false),
    (p_clinic_id, 'Soro - Mitocondrial', 'Endovenoso', 'Protocolos complexos', false),
    (p_clinic_id, 'Soro - Outros', 'Endovenoso', 'Protocolos complexos', false),
    (p_clinic_id, 'Soro - Performance', 'Endovenoso', 'Aceleradores Metabólicos', false),
    (p_clinic_id, 'Soro - Pele, cabelo e unha', 'Endovenoso', 'Vitaminas e Minerais', false),
    (p_clinic_id, 'Soro - Queima de gordura', 'Endovenoso', 'Aceleradores Metabólicos', false),
    (p_clinic_id, 'Soro - Vitamina B12', 'Endovenoso', 'Vitaminas e Minerais', false),
    (p_clinic_id, 'Soro - Vitamina C', 'Endovenoso', 'Vitaminas e Minerais', false),
    (p_clinic_id, 'Sublocação', 'Sublocação', 'Sublocação de espaço fixo', false),
    (p_clinic_id, 'Suplementação', 'Outros', 'Outros', false),
    (p_clinic_id, 'Terapia hormonal masculina', 'Intramuscular', 'Aplicação de hormônios (IM)', false),
    (p_clinic_id, 'Terapias injetáveis', 'Intramuscular', 'Protocolos complexos (IM)', false),
    (p_clinic_id, 'Teste ergométrico', 'Exames', 'Avaliação Clínica', false),
    (p_clinic_id, 'Tratamento de acne', 'Estética', 'Tratamentos rosto', false),
    (p_clinic_id, 'Tratamento de dor crônica', 'Outros', 'Outros', false),
    (p_clinic_id, 'Tratamento digestivo', 'Outros', 'Outros', false),
    (p_clinic_id, 'Tratamento hormonal', 'Outros', 'Outros', false),
    (p_clinic_id, 'Tratamento respiratório', 'Outros', 'Outros', false),
    (p_clinic_id, 'Triancinolona', 'Intramuscular', 'Antiinflamatórios (IM)', false),
    (p_clinic_id, 'Ultrassom', 'Exames de Imagem', 'Ultrassom', false),
    (p_clinic_id, 'Ultrassonografia obstétrica', 'Exames de Imagem', 'Ultrassom', false),
    (p_clinic_id, 'Vasectomia', 'Procedimentos', 'Cirurgia em centro cirúrgico', false),
    (p_clinic_id, 'Vitamina D3 - 600.000ui', 'Intramuscular', 'Vitaminas e Minerais (IM)', false)
  ON CONFLICT DO NOTHING;
END;
$function$;